
[web]
app-instance ansible_host=172.31.52.230 ansible_user=ubuntu ansible_ssh_private_key_file=~/tech515-oliver-aws.pem

[db]
db-instance ansible_host=172.31.56.26 ansible_user=ubuntu ansible_ssh_private_key_file=~/tech515-oliver-aws.pem